#!/usr/bin/env python3
# AI: Claude Code | Opus 4.6 | 2026 March 04 | Purpose: Create project-specific species to phyloname mapping
# Human: Eric Edsinger

"""
PROJECT-SPECIFIC SPECIES MAPPING GENERATOR

================================================================================
SCRIPT PURPOSE (For Non-Programmers):
================================================================================
This script creates a mapping file for YOUR specific project species.

Instead of using the massive full NCBI taxonomy mapping (~700MB), this creates
a small, focused file containing only the species you're working with.

EXAMPLE:
If your project has 3 species (Human, Aplysia, Octopus), this creates a
simple 4-line file (1 header + 3 species) that maps:
  Homo_sapiens -> Metazoa_Chordata_Mammalia_Primates_Hominidae_Homo_sapiens

INPUT:
A simple text file with one species per line (Genus_species format):
  Homo_sapiens
  Aplysia_californica
  Octopus_bimaculoides

OUTPUT:
A TSV mapping file with columns:
  genus_species | phyloname | phyloname_taxonid

HANDLING SPECIES NOT IN NCBI TAXONOMY:
Some species may not appear in NCBI's taxonomy database. This can happen when:
  - The species was recently described and not yet in NCBI
  - The species name uses a non-standard spelling
  - The species is from a specialized database not reflected in NCBI

These species are NEVER dropped. Instead, they receive a placeholder phyloname
using NOTINNCBI markers at every taxonomic level:

  Chromosphaera_perkinsii -> NOTINNCBI_NOTINNCBI_NOTINNCBI_NOTINNCBI_NOTINNCBI_Chromosphaera_perkinsii

This ensures:
  1. ALL species from the species list appear in the output (none are lost)
  2. The NOTINNCBI markers are clearly visible and searchable
  3. Users can provide proper phylonames via Script 004 (user_phylonames)
  4. Downstream scripts receive a complete species set

================================================================================
TECHNICAL NOTES (For Python/CS Experts):
================================================================================
- Reads the master mapping file generated by script 002
- Creates indexed lookup for fast species matching
- Handles multiple matches (warns if found)
- Species not in NCBI get NOTINNCBI placeholder phylonames (never dropped)
- Output suitable for direct use in downstream subprojects
"""

from pathlib import Path
from typing import Dict, List, Tuple, Optional
import sys
import argparse
from datetime import datetime


def generate_notinncbi_phyloname( genus_species: str ) -> Tuple[ str, str ]:
    """
    Generate a placeholder phyloname for species not found in NCBI taxonomy.

    The phyloname format requires Kingdom_Phylum_Class_Order_Family_Genus_species.
    For species not in NCBI, we fill all higher taxonomy levels with NOTINNCBI
    and preserve the Genus_species from the user's input.

    Args:
        genus_species: Species name in Genus_species format (e.g., Chromosphaera_perkinsii)

    Returns:
        Tuple of (phyloname, phyloname_taxonid) with NOTINNCBI markers
    """
    # Split genus_species to extract genus and species parts
    parts_genus_species = genus_species.split( '_' )
    genus = parts_genus_species[ 0 ]
    species = '_'.join( parts_genus_species[ 1: ] ) if len( parts_genus_species ) > 1 else ''

    # Build phyloname: NOTINNCBI for Kingdom, Phylum, Class, Order, Family + actual Genus_species
    phyloname = f"NOTINNCBI_NOTINNCBI_NOTINNCBI_NOTINNCBI_NOTINNCBI_{genus}_{species}" if species else f"NOTINNCBI_NOTINNCBI_NOTINNCBI_NOTINNCBI_NOTINNCBI_{genus}"

    # Taxon ID is 0 (unknown) for species not in NCBI
    phyloname_taxonid = f"{phyloname}___0"

    return phyloname, phyloname_taxonid


def load_master_mapping( mapping_file_path: Path ) -> Dict[ str, Tuple[ str, str ] ]:
    """
    Load the master phyloname mapping file into a dictionary.

    The dictionary maps genus_species -> (phyloname, phyloname_taxonid)

    Args:
        mapping_file_path: Path to the master mapping TSV file

    Returns:
        Dictionary mapping genus_species to (phyloname, phyloname_taxonid) tuples
    """
    genus_species___phylonames = {}

    print( f"Loading master mapping from: {mapping_file_path}" )

    # phyloname	phyloname_taxonid	genus_species	taxon_id	...
    # Metazoa_Chordata_Mammalia_Primates_Hominidae_Homo_sapiens	Metazoa_Chordata_..___9606	Homo_sapiens	9606	...
    with open( mapping_file_path, 'r', encoding = 'utf-8' ) as input_file:
        # Skip header
        header = input_file.readline()

        for line in input_file:
            line = line.strip()
            if not line:
                continue

            parts = line.split( '\t' )
            if len( parts ) < 3:
                continue

            phyloname = parts[ 0 ]
            phyloname_taxonid = parts[ 1 ]
            genus_species = parts[ 2 ]

            # Store in dictionary
            # Note: Some genus_species may have multiple entries (different taxon IDs)
            # We take the first one encountered
            if genus_species not in genus_species___phylonames:
                genus_species___phylonames[ genus_species ] = ( phyloname, phyloname_taxonid )

    print( f"  Loaded {len( genus_species___phylonames ):,} unique genus_species entries" )

    return genus_species___phylonames


def load_species_list( species_list_path: Path ) -> List[ str ]:
    """
    Load the user's species list.

    Args:
        species_list_path: Path to the species list file (one species per line)

    Returns:
        List of species names (Genus_species format)
    """
    species_list = []

    print( f"Loading species list from: {species_list_path}" )

    with open( species_list_path, 'r', encoding = 'utf-8' ) as input_file:
        for line in input_file:
            line = line.strip()
            # Skip empty lines and comments
            if not line or line.startswith( '#' ):
                continue
            species_list.append( line )

    print( f"  Found {len( species_list )} species" )

    return species_list


def create_project_mapping(
    species_list: List[ str ],
    genus_species___phylonames: Dict[ str, Tuple[ str, str ] ],
    output_file_path: Path
) -> Tuple[ int, int, List[ str ] ]:
    """
    Create the project-specific mapping file.

    ALL species from the species list are included in the output.
    Species not found in NCBI taxonomy receive NOTINNCBI placeholder phylonames.

    Args:
        species_list: List of species names to map
        genus_species___phylonames: Master mapping dictionary
        output_file_path: Path for output TSV file

    Returns:
        Tuple of (found_count, notinncbi_count, notinncbi_species_list)
    """
    found_count = 0
    notinncbi_count = 0
    notinncbi_species = []

    print( f"Creating project mapping: {output_file_path}" )

    with open( output_file_path, 'w', encoding = 'utf-8' ) as output_file:
        # Write header
        header = 'genus_species\tphyloname\tphyloname_taxonid\n'
        output_file.write( header )

        for species in species_list:
            if species in genus_species___phylonames:
                phyloname, phyloname_taxonid = genus_species___phylonames[ species ]
                output = f"{species}\t{phyloname}\t{phyloname_taxonid}\n"
                output_file.write( output )
                found_count += 1
            else:
                # Species not in NCBI - generate NOTINNCBI placeholder phyloname
                phyloname, phyloname_taxonid = generate_notinncbi_phyloname( species )
                output = f"{species}\t{phyloname}\t{phyloname_taxonid}\n"
                output_file.write( output )
                notinncbi_species.append( species )
                notinncbi_count += 1

    return found_count, notinncbi_count, notinncbi_species


def main():
    """Main execution function."""

    # Parse command line arguments
    parser = argparse.ArgumentParser(
        description = 'Create project-specific species to phyloname mapping',
        formatter_class = argparse.RawDescriptionHelpFormatter,
        epilog = """
Examples:
  python3 003_ai-python-create_species_mapping.py \\
      --species-list INPUT_user/species_list.txt \\
      --output output_to_input/maps/project_map-genus_species_X_phylonames.tsv

  python3 003_ai-python-create_species_mapping.py \\
      --species-list my_species.txt \\
      --master-mapping 2-output/map-phyloname_X_ncbi_taxonomy_info.tsv \\
      --output my_project_mapping.tsv
        """
    )

    parser.add_argument(
        '--species-list',
        type = str,
        required = True,
        help = 'Path to species list file (one Genus_species per line)'
    )

    parser.add_argument(
        '--output',
        type = str,
        required = True,
        help = 'Path for output mapping TSV file'
    )

    parser.add_argument(
        '--master-mapping',
        type = str,
        default = '2-output/map-phyloname_X_ncbi_taxonomy_info.tsv',
        help = 'Path to master phyloname mapping file (default: 2-output/map-phyloname_X_ncbi_taxonomy_info.tsv)'
    )

    args = parser.parse_args()

    # Convert to Path objects
    species_list_path = Path( args.species_list )
    output_file_path = Path( args.output )
    master_mapping_path = Path( args.master_mapping )

    print( "=" * 70 )
    print( "GIGANTIC Project Species Mapping Generator" )
    print( "=" * 70 )
    print( "" )

    # Verify input files exist
    if not species_list_path.exists():
        print( f"ERROR: Species list file not found: {species_list_path}" )
        sys.exit( 1 )

    if not master_mapping_path.exists():
        print( f"ERROR: Master mapping file not found: {master_mapping_path}" )
        print( "Run 002_ai-python-generate_phylonames.py first." )
        sys.exit( 1 )

    # Ensure output directory exists
    output_file_path.parent.mkdir( parents = True, exist_ok = True )

    # Load master mapping
    genus_species___phylonames = load_master_mapping( master_mapping_path )

    # Load species list
    species_list = load_species_list( species_list_path )

    if not species_list:
        print( "ERROR: No species found in species list file" )
        sys.exit( 1 )

    # Create project mapping (ALL species included - none dropped)
    print( "" )
    found_count, notinncbi_count, notinncbi_species = create_project_mapping(
        species_list = species_list,
        genus_species___phylonames = genus_species___phylonames,
        output_file_path = output_file_path
    )

    # Report results
    print( "" )
    print( "=" * 70 )
    print( "Mapping Complete!" )
    print( "=" * 70 )
    print( f"Species in NCBI taxonomy: {found_count}" )
    print( f"Species NOT in NCBI taxonomy: {notinncbi_count}" )
    print( f"Total species in output: {found_count + notinncbi_count}" )
    print( "" )

    if notinncbi_species:
        print( "WARNING: The following species were NOT found in NCBI taxonomy." )
        print( "They have been assigned NOTINNCBI placeholder phylonames." )
        print( "" )
        print( "NOTINNCBI species:" )
        for species in notinncbi_species:
            print( f"  - {species}" )
        print( "" )
        print( "WHAT TO DO:" )
        print( "  These species need proper phylonames. You have two options:" )
        print( "" )
        print( "  1. PROVIDE USER PHYLONAMES (recommended):" )
        print( "     Create a user_phylonames file and set user_phylonames in" )
        print( "     START_HERE-user_config.yaml. Script 004 will apply your phylonames" )
        print( "     and mark overridden clades as UNOFFICIAL." )
        print( "" )
        print( "  2. CHECK SPECIES SPELLING:" )
        print( "     The species name may be different in NCBI. Check:" )
        print( "     https://www.ncbi.nlm.nih.gov/taxonomy" )
        print( "" )

    print( f"Output file: {output_file_path}" )
    print( "" )
    print( "This mapping file can be used by other GIGANTIC subprojects." )
    print( "=" * 70 )


if __name__ == '__main__':
    main()
