#!/usr/bin/env python3
# AI: Claude Code | Opus 4.5 | 2026 February 12 | Purpose: Write run log to research notebook
# Human: Eric Edsinger
"""
Write Run Log to Research Notebook

This script creates a timestamped log entry in the research notebook
for transparency and reproducibility - like an AI lab notebook.

Output location:
    research_notebook/research_ai/subproject-genomesDB/logs/
"""

import argparse
import os
from datetime import datetime
from pathlib import Path


def find_project_root( start_path: Path ) -> Path:
    """
    Find the project root by looking for gigantic_project-* directory.
    """
    current = start_path.resolve()

    while current != current.parent:
        # Check if we're in a gigantic_project-* directory
        if current.name.startswith( 'gigantic_project-' ):
            return current
        current = current.parent

    # Fallback: go up 5 levels from workflow (workflow -> STEP_1 -> genomesDB -> subprojects -> project)
    return start_path.resolve().parents[ 4 ]


def write_run_log(
    project_name: str,
    proteome_count: int,
    manifest_file: str,
    output_dir: str,
    status: str
):
    """
    Write a run log entry to the research notebook.
    """
    # Find project root
    script_path = Path( __file__ ).resolve()
    project_root = find_project_root( script_path )

    # Create log directory
    log_dir = project_root / 'research_notebook' / 'research_ai' / 'subproject-genomesDB' / 'logs'
    log_dir.mkdir( parents = True, exist_ok = True )

    # Generate timestamp and log filename
    timestamp = datetime.now()
    log_filename = f"ingest_sources_{timestamp.strftime( '%Y%m%d_%H%M%S' )}.md"
    log_path = log_dir / log_filename

    # Write log entry
    with open( log_path, 'w' ) as output_log:
        output = f"# GIGANTIC Source Proteome Ingestion Log\n\n"
        output += f"**Workflow**: STEP_1-sources/workflow-COPYME-ingest_source_proteomes\n"
        output += f"**Timestamp**: {timestamp.strftime( '%Y-%m-%d %H:%M:%S' )}\n"
        output += f"**Status**: {status.upper()}\n\n"
        output_log.write( output )

        output = f"## Configuration\n\n"
        output += f"- **Project**: {project_name}\n"
        output += f"- **Proteomes ingested**: {proteome_count}\n"
        output += f"- **Source manifest**: {manifest_file}\n"
        output += f"- **Output directory**: {output_dir}\n\n"
        output_log.write( output )

        output = f"## What This Run Did\n\n"
        output += f"1. Read source manifest listing {proteome_count} proteome files\n"
        output += f"2. Validated that all source files exist\n"
        output += f"3. Hard copied proteomes to OUTPUT_pipeline/1-output/proteomes/\n"
        output += f"4. Created symlinks in STEP_1-sources/output_to_input/proteomes/\n\n"
        output_log.write( output )

        output = f"## Next Steps\n\n"
        output += f"Run STEP_2-standardize_and_evaluate to:\n"
        output += f"- Standardize proteome file formats\n"
        output += f"- Apply phyloname-based naming convention\n"
        output += f"- Evaluate genome/proteome quality\n\n"
        output_log.write( output )

        output = f"---\n"
        output += f"*Log generated by GIGANTIC AI workflow*\n"
        output_log.write( output )

    print( f"Run log written to: {log_path}" )

    return log_path


def main():
    parser = argparse.ArgumentParser(
        description = 'Write run log to research notebook'
    )
    parser.add_argument(
        '--project-name',
        type = str,
        required = True,
        help = 'Project name'
    )
    parser.add_argument(
        '--proteome-count',
        type = int,
        required = True,
        help = 'Number of proteomes ingested'
    )
    parser.add_argument(
        '--manifest-file',
        type = str,
        required = True,
        help = 'Path to source manifest file'
    )
    parser.add_argument(
        '--output-dir',
        type = str,
        required = True,
        help = 'Output directory'
    )
    parser.add_argument(
        '--status',
        type = str,
        choices = [ 'success', 'failed' ],
        default = 'success',
        help = 'Run status'
    )

    args = parser.parse_args()

    write_run_log(
        project_name = args.project_name,
        proteome_count = args.proteome_count,
        manifest_file = args.manifest_file,
        output_dir = args.output_dir,
        status = args.status
    )


if __name__ == '__main__':
    main()
