#!/usr/bin/env python3
# AI: Claude Code | Opus 4.5 | 2026 February 05 | Purpose: Create project-specific species to phyloname mapping
# Human: Eric Edsinger

"""
PROJECT-SPECIFIC SPECIES MAPPING GENERATOR

================================================================================
SCRIPT PURPOSE (For Non-Programmers):
================================================================================
This script creates a mapping file for YOUR specific project species.

Instead of using the massive full NCBI taxonomy mapping (~700MB), this creates
a small, focused file containing only the species you're working with.

EXAMPLE:
If your project has 3 species (Human, Aplysia, Octopus), this creates a
simple 4-line file (1 header + 3 species) that maps:
  Homo_sapiens -> Metazoa_Chordata_Mammalia_Primates_Hominidae_Homo_sapiens

INPUT:
A simple text file with one species per line (Genus_species format):
  Homo_sapiens
  Aplysia_californica
  Octopus_bimaculoides

OUTPUT:
A TSV mapping file with columns:
  genus_species | phyloname | phyloname_taxonid

================================================================================
TECHNICAL NOTES (For Python/CS Experts):
================================================================================
- Reads the master mapping file generated by script 002
- Creates indexed lookup for fast species matching
- Handles multiple matches (warns if found)
- Exits with error if any species not found (fail-fast)
- Output suitable for direct use in downstream subprojects
"""

from pathlib import Path
from typing import Dict, List, Tuple, Optional
import sys
import argparse
from datetime import datetime


def load_master_mapping( mapping_file_path: Path ) -> Dict[ str, Tuple[ str, str ] ]:
    """
    Load the master phyloname mapping file into a dictionary.

    The dictionary maps genus_species -> (phyloname, phyloname_taxonid)

    Args:
        mapping_file_path: Path to the master mapping TSV file

    Returns:
        Dictionary mapping genus_species to (phyloname, phyloname_taxonid) tuples
    """
    genus_species___phylonames = {}

    print( f"Loading master mapping from: {mapping_file_path}" )

    # phyloname	phyloname_taxonid	genus_species	taxon_id	...
    # Metazoa_Chordata_Mammalia_Primates_Hominidae_Homo_sapiens	Metazoa_Chordata_..___9606	Homo_sapiens	9606	...
    with open( mapping_file_path, 'r', encoding = 'utf-8' ) as input_file:
        # Skip header
        header = input_file.readline()

        for line in input_file:
            line = line.strip()
            if not line:
                continue

            parts = line.split( '\t' )
            if len( parts ) < 3:
                continue

            phyloname = parts[ 0 ]
            phyloname_taxonid = parts[ 1 ]
            genus_species = parts[ 2 ]

            # Store in dictionary
            # Note: Some genus_species may have multiple entries (different taxon IDs)
            # We take the first one encountered
            if genus_species not in genus_species___phylonames:
                genus_species___phylonames[ genus_species ] = ( phyloname, phyloname_taxonid )

    print( f"  Loaded {len( genus_species___phylonames ):,} unique genus_species entries" )

    return genus_species___phylonames


def load_species_list( species_list_path: Path ) -> List[ str ]:
    """
    Load the user's species list.

    Args:
        species_list_path: Path to the species list file (one species per line)

    Returns:
        List of species names (Genus_species format)
    """
    species_list = []

    print( f"Loading species list from: {species_list_path}" )

    with open( species_list_path, 'r', encoding = 'utf-8' ) as input_file:
        for line in input_file:
            line = line.strip()
            # Skip empty lines and comments
            if not line or line.startswith( '#' ):
                continue
            species_list.append( line )

    print( f"  Found {len( species_list )} species" )

    return species_list


def create_project_mapping(
    species_list: List[ str ],
    genus_species___phylonames: Dict[ str, Tuple[ str, str ] ],
    output_file_path: Path
) -> Tuple[ int, int ]:
    """
    Create the project-specific mapping file.

    Args:
        species_list: List of species names to map
        genus_species___phylonames: Master mapping dictionary
        output_file_path: Path for output TSV file

    Returns:
        Tuple of (found_count, missing_count)
    """
    found_count = 0
    missing_count = 0
    missing_species = []

    print( f"Creating project mapping: {output_file_path}" )

    with open( output_file_path, 'w', encoding = 'utf-8' ) as output_file:
        # Write header
        header = 'genus_species\tphyloname\tphyloname_taxonid\n'
        output_file.write( header )

        for species in species_list:
            if species in genus_species___phylonames:
                phyloname, phyloname_taxonid = genus_species___phylonames[ species ]
                output = f"{species}\t{phyloname}\t{phyloname_taxonid}\n"
                output_file.write( output )
                found_count += 1
            else:
                missing_species.append( species )
                missing_count += 1

    return found_count, missing_count, missing_species


def main():
    """Main execution function."""

    # Parse command line arguments
    parser = argparse.ArgumentParser(
        description = 'Create project-specific species to phyloname mapping',
        formatter_class = argparse.RawDescriptionHelpFormatter,
        epilog = """
Examples:
  python3 003_ai-python-create_species_mapping.py \\
      --species-list INPUT_user/species_list.txt \\
      --output output_to_input/maps/project_map-genus_species_X_phylonames.tsv

  python3 003_ai-python-create_species_mapping.py \\
      --species-list my_species.txt \\
      --master-mapping output/2-output/map-phyloname_X_ncbi_taxonomy_info.tsv \\
      --output my_project_mapping.tsv
        """
    )

    parser.add_argument(
        '--species-list',
        type = str,
        required = True,
        help = 'Path to species list file (one Genus_species per line)'
    )

    parser.add_argument(
        '--output',
        type = str,
        required = True,
        help = 'Path for output mapping TSV file'
    )

    parser.add_argument(
        '--master-mapping',
        type = str,
        default = 'output/2-output/map-phyloname_X_ncbi_taxonomy_info.tsv',
        help = 'Path to master phyloname mapping file (default: output/2-output/map-phyloname_X_ncbi_taxonomy_info.tsv)'
    )

    parser.add_argument(
        '--allow-missing',
        action = 'store_true',
        help = 'Allow missing species (default: exit with error if any species not found)'
    )

    args = parser.parse_args()

    # Convert to Path objects
    species_list_path = Path( args.species_list )
    output_file_path = Path( args.output )
    master_mapping_path = Path( args.master_mapping )

    print( "=" * 70 )
    print( "GIGANTIC Project Species Mapping Generator" )
    print( "=" * 70 )
    print( "" )

    # Verify input files exist
    if not species_list_path.exists():
        print( f"ERROR: Species list file not found: {species_list_path}" )
        sys.exit( 1 )

    if not master_mapping_path.exists():
        print( f"ERROR: Master mapping file not found: {master_mapping_path}" )
        print( "Run 002_ai-python-generate_phylonames.py first." )
        sys.exit( 1 )

    # Ensure output directory exists
    output_file_path.parent.mkdir( parents = True, exist_ok = True )

    # Load master mapping
    genus_species___phylonames = load_master_mapping( master_mapping_path )

    # Load species list
    species_list = load_species_list( species_list_path )

    if not species_list:
        print( "ERROR: No species found in species list file" )
        sys.exit( 1 )

    # Create project mapping
    print( "" )
    found_count, missing_count, missing_species = create_project_mapping(
        species_list = species_list,
        genus_species___phylonames = genus_species___phylonames,
        output_file_path = output_file_path
    )

    # Report results
    print( "" )
    print( "=" * 70 )
    print( "Mapping Complete!" )
    print( "=" * 70 )
    print( f"Species found: {found_count}" )
    print( f"Species missing: {missing_count}" )
    print( "" )

    if missing_species:
        print( "Missing species:" )
        for species in missing_species:
            print( f"  - {species}" )
        print( "" )

        if not args.allow_missing:
            print( "ERROR: Some species were not found in the NCBI taxonomy." )
            print( "Check spelling or use --allow-missing to continue anyway." )
            sys.exit( 1 )
        else:
            print( "WARNING: Continuing with missing species (--allow-missing flag set)" )

    print( f"Output file: {output_file_path}" )
    print( "" )
    print( "This mapping file can be used by other GIGANTIC subprojects." )
    print( "=" * 70 )


if __name__ == '__main__':
    main()
