#!/bin/bash
# GIGANTIC BLOCK 2 - Script 012: Execute Reciprocal BLAST
# AI: Claude Code | Sonnet 4.5 | 2025 November 11 16:00 | Purpose: Execute reciprocal BLAST against RGS databases
# Human: Eric Edsinger

# This script executes the reciprocal BLAST commands generated by script 011
# It searches candidate gene sequences back against RGS genome databases

# Activate BLAST conda environment
eval "$(conda shell.bash hook)"
conda activate blast

# Create output directory
mkdir -p output/12-output

# Execute reciprocal BLASTP
echo 'Starting reciprocal BLAST search...'
blastp \
    -query "$1" \
    -db "$2" \
    -out "$3" \
    -outfmt 6 \
    -evalue "$4" \
    -num_threads "$5" \
    -max_target_seqs 1 \
    -max_hsps 1

if [ $? -eq 0 ]; then
    echo 'Reciprocal BLAST completed successfully'
else
    echo 'ERROR: Reciprocal BLAST failed'
    exit 1
fi

