#!/usr/bin/env python3
# GIGANTIC BLOCK 2 - Script 010: Generate Makeblastdb Commands
# AI: Claude Code | Sonnet 4.5 | 2025 November 08 18:00 | Purpose: Generate makeblastdb commands for reciprocal BLAST databases
# Human: Eric Edsinger

"""
Generate Makeblastdb Commands for Reciprocal BLAST

This script generates shell commands to create BLAST databases from model organism
fastas and RGS sequences. These databases are needed for reciprocal BLAST analysis
where candidate gene sequences are searched against RGS genomes.

The databases created include:
1. Model organism protein databases (human, fly, worm, etc.)
2. RGS database with genome identifiers

Workflow Context:
    Script 008 → Mappings → Script 009 → FASTA list → **Script 010** → Commands → Script 011
    
Input Files:
    - output/8-output/8_ai-list-model-organism-fastas-with-rgs-headers.txt - FASTA files to index
    
Output Files:
    - 11-makeblastdb-commands.sh - Executable shell script with makeblastdb commands

Usage:
    python3 010_ai-python-generate_makeblastdb_commands.py \\
        --fasta-list output/8-list-model-organism-fastas-with-rgs-headers.txt \\
        --output-script 11-makeblastdb-commands.sh \\
        --conda-env blast
"""

import argparse
import logging
import sys
from pathlib import Path
from typing import List
from datetime import datetime


def setup_logging() -> logging.Logger:
    """Configure logging with timestamps and levels."""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )
    return logging.getLogger( __name__ )


def read_fasta_list( list_file: Path, logger: logging.Logger ) -> List[Path]:
    """
    Read list of FASTA file paths.
    
    Args:
        list_file: File containing FASTA paths
        logger: Logger instance
        
    Returns:
        List of FASTA file paths
    """
    logger.info( f"Reading FASTA list from: {list_file}" )
    
    fasta_paths = []
    
    with open( list_file, 'r' ) as input_list:
        for line in input_list:
            line = line.strip()
            if line:
                fasta_paths.append( Path( line ) )
    
    logger.info( f"Found {len( fasta_paths )} FASTA files to index" )
    
    return fasta_paths


def generate_makeblastdb_commands(
    fasta_paths: List[Path],
    conda_env: str,
    logger: logging.Logger
) -> List[str]:
    """
    Generate makeblastdb commands for each FASTA file.
    
    Args:
        fasta_paths: List of FASTA file paths
        conda_env: Conda environment name for BLAST
        logger: Logger instance
        
    Returns:
        List of shell command strings
    """
    logger.info( "\nGenerating makeblastdb commands..." )
    
    commands = []
    
    for fasta_path in fasta_paths:
        # Create database name from FASTA filename
        database_name = f"{fasta_path.stem}-blastdb"
        
        # Generate makeblastdb command
        command = (
            f"makeblastdb "
            f"-in {fasta_path} "
            f"-dbtype prot "
            f"-out output/{database_name} "
            f"-parse_seqids"
        )
        
        commands.append( command )
        logger.info( f"  {fasta_path.name} → {database_name}" )
    
    return commands


def write_makeblastdb_script(
    output_script: Path,
    commands: List[str],
    conda_env: str,
    logger: logging.Logger
) -> None:
    """
    Write makeblastdb commands to executable shell script.
    
    Args:
        output_script: Output script file path
        commands: List of makeblastdb commands
        conda_env: Conda environment name
        logger: Logger instance
    """
    logger.info( f"\nWriting makeblastdb script: {output_script}" )
    
    with open( output_script, 'w' ) as output_file:
        # Write header
        output_file.write( "#!/bin/bash\n" )
        output_file.write( "# AI: Claude Code | Sonnet 4.5 | 2025 November 08 | Purpose: Create BLAST databases for reciprocal analysis\n" )
        output_file.write( "# Human: Eric Edsinger\n" )
        output_file.write( f"# Generated by: 010_ai-python-generate_makeblastdb_commands.py\n\n" )
        
        # Activate conda environment
        output_file.write( f"# Activate BLAST conda environment\n" )
        output_file.write( f"eval \"$(conda shell.bash hook)\"\n" )
        output_file.write( f"conda activate {conda_env}\n\n" )
        
        # Write commands
        output_file.write( f"# Create BLAST databases ({len( commands )} total)\n" )
        for index, command in enumerate( commands, 1 ):
            output_file.write( f"\n# Database {index}\n" )
            output_file.write( f"{command}\n" )
        
        # Final message
        output_file.write( f"\necho ''\n" )
        output_file.write( f"echo 'Created {len( commands )} BLAST databases successfully'\n" )
    
    # Make script executable
    output_script.chmod( 0o755 )
    
    logger.info( f"Wrote {len( commands )} makeblastdb commands" )
    logger.info( f"Script is executable: chmod +x completed" )


def main():
    """Main execution function."""
    parser = argparse.ArgumentParser(
        description='Generate makeblastdb commands for reciprocal BLAST databases'
    )
    
    parser.add_argument(
        '--fasta-list',
        type=str,
        required=True,
        help='File containing list of FASTA files to index'
    )
    
    parser.add_argument(
        '--output-script',
        type=str,
        required=True,
        help='Output shell script file'
    )
    
    parser.add_argument(
        '--conda-env',
        type=str,
        default='blast',
        help='Conda environment for BLAST (default: blast)'
    )
    
    arguments = parser.parse_args()
    logger = setup_logging()
    
    # Log script start
    logger.info( "=" * 80 )
    logger.info( "Generate Makeblastdb Commands" )
    logger.info( "=" * 80 )
    logger.info( f"Script started at: {datetime.now().strftime( '%Y-%m-%d %H:%M:%S' )}" )
    
    # Convert paths
    fasta_list_file = Path( arguments.fasta_list )
    output_script_file = Path( arguments.output_script )
    
    # Validate input
    if not fasta_list_file.exists():
        logger.error( f"FASTA list file not found: {fasta_list_file}" )
        sys.exit( 1 )
    
    # Read FASTA list
    fasta_paths = read_fasta_list( fasta_list_file, logger )
    
    if not fasta_paths:
        logger.error( "No FASTA files found in list!" )
        sys.exit( 1 )
    
    # Generate commands
    commands = generate_makeblastdb_commands( fasta_paths, arguments.conda_env, logger )
    
    # Write script
    write_makeblastdb_script( output_script_file, commands, arguments.conda_env, logger )
    
    # Summary
    logger.info( "\n" + "=" * 80 )
    logger.info( "SCRIPT COMPLETE" )
    logger.info( "=" * 80 )
    logger.info( f"Generated script: {output_script_file}" )
    logger.info( f"Total makeblastdb commands: {len( commands )}" )
    logger.info( f"\nTo execute: ./{output_script_file}" )
    logger.info( f"\nScript completed at: {datetime.now().strftime( '%Y-%m-%d %H:%M:%S' )}" )


if __name__ == '__main__':
    main()

